version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_ssl:/etc/nginx/ssl:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"
    depends_on:
      - wiremock
      - imock

  wiremock:
    image: wiremock/wiremock:latest
    restart: always
    expose:
      - "8080"
      - "8443"
    volumes:
      - ./mappings:/home/wiremock/mappings
    command: >
      --https-port 8443
      --verbose
      --enable-browser-proxying
      --disable-banner

  imock:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8001"
    environment:
      - PORT=8001
      - DOCKER_CONTAINER=true 